apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-weatherapp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-weatherapp
spec:
  source:
    git:
      url: https://github.com/bagreda-vmw/my-weatherapp
      ref:
        branch: main
