apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-weatherapp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-weatherapp
<<<<<<< HEAD
=======
    apps.tanzu.vmware.com/has-tests: "true"
>>>>>>> 990df43cc71c818449beb87de489fd2ef5da70c8
spec:
  source:
    git:
      url: https://github.com/bagreda-vmw/my-weatherapp
      ref:
        branch: main
